linters:
  enable:
  - errcheck
  - goconst
  - gofmt
  - revive
  - gosec
  - govet
  - ineffassign
  - lll
  - gosimple
  - staticcheck
  - unused
  - misspell
  - nakedret
  - unconvert
  enable-all: false
run:
  skip-files:
  - schema.go
  - pulumiManifest.go
  - doc.go
  timeout: 20m
